<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<?php $ads = $this->getAds(); ?>
<div class="blog-adspace">



<?php $search = ''; ?>
<?php $search = Mage::registry('blog_search') ?>
<div class="blog-search">
	<form action="/blog/index/search/" method="post">
		<label>Search</label>
		<div class="cf">
			<input type="text" name="search" value="<?php echo $search ?>" />
			<button type="submit">Go</button>
		</div>
	</form>
</div>


	<a href="<?php echo $ads->getData('side_ad_1_link') ?>">
		<img src="/media<?php echo $ads->getData('side_ad_1') ?>" alt="" />
	</a>

	<a href="<?php echo $ads->getData('side_ad_2_link') ?>" class="middle-ad">
		<img src="/media<?php echo $ads->getData('side_ad_2') ?>" alt="" />
	</a>

	<a href="<?php echo $ads->getData('side_ad_3_link') ?>">
		<img src="/media<?php echo $ads->getData('side_ad_3') ?>" alt="" />
	</a>

</div>