<div class="blog">

	<div class="topper">
		<?php echo $this->getChildHtml('blog.nav') ?>
	</div>

	<div class="blog-space cf">
		<div class="blog-content">
			<?php echo $this->getChildHtml('blog.content') ?>
		</div>
		<div class="blog-sidebar">
			<?php echo $this->getChildHtml('blog.sidebar') ?>
		</div>
	</div>
</div>

<script type="text/javascript" data-pin-hover="true" src="//assets.pinterest.com/js/pinit.js"></script>

<Style>

/* Blog section*/

.main-container {
    width: 78%;
    margin: 0 auto;
}

.blog-entry-view .col-main {
  /*width: 78% !important;
  margin:0 auto 90px ;
  float: none;*/
}

.blog-entry-view .col-main, .blog-index-index .col-main, .blog-category-view .col-main {
  width: 75% !important;
  margin:0 auto 190px ;
  float: none;
}

.blog-popular {
	display: inline-block;
}

div.blog-popular .post {
	width: 140px;
	float: left;
	zoom: 1;
	margin-right: 28px;
	position: relative;
}

div.blog-popular .last {
	margin-right: 0 !important;
}

.blog-header a, .blog-header strong {
	font-size: 50px;
}
.blog-header strong {
	font-weight: bold;
}
.blog-space .instagram a {
	display: inline-flex;
}

.blog-entry-view a, .blog-index-index a, .blog-category-view a {
	text-decoration: none;
	color: #F27997;
}

.blog-entry-view fieldset, .blog-entry-view img, 
.blog-index-index fieldset, .blog-index-index img {
	border: 0;
}

.blog-adspace img {
	width: 100%;
	margin-top: 10px;
}

.blog-entry-view img, .blog-index-index img {
	vertical-align: top;
}

div.blog-popular .post .overlay {
	position: absolute;
	top: 1px;
	left: 0px;
	width: 140px;
	height: 140px;
}

div.blog-popular .post .overlay p.post-name {
	color: #fff;
	font-size: 22px;
	position: absolute;
	bottom: 15px;
	left: 10px;
	text-transform: lowercase;
}

.blog-header {
	text-align: center;
	margin: 30px 0 15px;
	font-size: 50px;
	font-weight: 400;
	text-transform: lowercase;
}

.blog-header a {
	color: #eb1c74;
}

div.blog-navigation {
	background: #f5f5f6;
	padding: 20px 60px;
	margin: 20px 0;
	display: inline-block;
}

div.blog-navigation div.category {
	float: left;
	zoom: 1;
	margin-right: 100px;
}

div.blog-navigation div.last {
	margin-right: 0 !important;
}

div.blog-navigation div.category a {
	font-size: 17px;
	text-transform: lowercase;
	color: #797979;
	font-weight: 300;
}

.blog-entry-view div.select-wrapper, .blog-index-index div.select-wrapper {
  width: 251px;
  background: url('../images/select-arrow.png') no-repeat right 1px;
  border: 1px solid #d3d3d4;
  height: 15px;
  padding: 7px 8px 6px;
  -webkit-box-shadow: inset 1px 1px 1px 1px #e1e1e1;
  box-shadow: inset 1px 1px 1px 1px #e1e1e1;
  cursor: pointer;
}
.blog-entry-view div.select-wrapper select, .blog-index-index div.select-wrapper select  {
  background: none;
  border: 0;
  width: 270px;
  -webkit-appearance: none;
  text-transform: lowercase;
}
.blog-entry-view div.select-wrapper option, .blog-index-index div.select-wrapper option {
  text-transform: lowercase;
}
.blog .blog-content {
  width: 620px;
  float: left;
  zoom: 1;
}
div.blog-content .entry:first-child {
  padding-top: 0px;
}
div.blog-content .entry {
  padding-bottom: 20px;
  border-bottom: 1px dashed #bebebe;
  padding-top: 20px;
}
div.blog-image img {
  width: 100%;
}
.blog-entry-view .entry h1.title, .blog-index-index .entry h1.title, 
div.blog-content .entry h1.title a {
  color: #eb1c74;
  font-size: 28px;
  font-weight: 300;
  text-transform: lowercase;
  margin-top: 20px;
}
div.blog-content .entry h5.date {
  color: #f27997;
  font-size: 15px;
  font-weight: 300;
}
div.blog-content .entry div.blog-copy {
  margin: 20px 0;
  font-weight: 300;
  color: #a1a1a5;
  font-size: 14px;
}
div.blog-adspace {
  width: 300px;
  padding: 15px;
  margin-left: 30px;
  float: left;
}
.blog-search {
  margin-bottom: 20px;
}
.blog-entry-view form, .blog-index-index form {
  display: inline;
}
.blog-search label {
  font-size: 24px;
  text-transform: lowercase;
  font-weight: 500;
  color: #eb1c74;
  display: block;
  margin-bottom: 10px;
}
.blog-entry-view label, .blog-index-index label {
  cursor: default;
}
.blog-search input {
  width: 84%;
  padding: 5px 0 7px;
  text-indent: 5px;
  float: left;
  zoom: 1;
}
.blog-search button {
  width: 14%;
  float: right;
  zoom: 1;
  padding: 5px 0 7px;
  background: #eb1c74;
  border: 0;
  color: #fff;
  text-transform: lowercase;
  font-size: 15px;
}
.blog-entry-view button, .blog-index-index button {
  cursor: pointer;
}
div.blog-adspace div.facebook {
  background: #fff;
  margin: 20px 0;
}
.blog-entry-view .fb_iframe_widget, .blog-index-index .fb_iframe_widget {
  display: inline-block;
  position: relative;
}
.blog-entry-view .fb_iframe_widget span, .blog-index-index .fb_iframe_widget span {
  display: inline-block;
  position: relative;
  text-align: justify;
}
div.blog-adspace .middle-ad {
  display: block;
  margin: 20px 0;
}
.blog .hide {
	display: none;
}

.blog-entry-view .show-more, .blog-index-index .show-more, .blog-category-view .show-more {
	  background-color: #F5F5F6;
	  padding: 10px;
	  text-align: center;
	  font-size: 16px;
	  margin-top: 15px;
	  cursor: pointer;
	  color: #797979;
}

div.blog-content .entry div.blog-copy p {
  margin-bottom: 10px;
}

</Style>