<?php if ($this->getEntry()): ?>
	<?php $entry = $this->getEntry(); ?>
	<div class="entry">
		<?php if ($entry->getImage() != ''): ?>
		<div class="blog-image">
			<a href="/blog/entry/view/<?php echo $entry->getData('url_key') ?>">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$entry->getImage(); ?>" alt="" />
			</a>
		</div>
		<?php endif ?>
		<h1 class="title"><?php echo $entry->getTitle() ?></h1>
		<?php $stamp = strtotime($entry->getData('created_at')) ?>
		<h5 class="date"><?php echo date('m/d/Y', $stamp); ?></h5>
		<div class="blog-copy">
			<?php echo $this->helper('cms')->getBlockTemplateProcessor()->filter($entry->getContent()) ?>
		</div>

		<div id="disqus_thread"></div>
	    <script type="text/javascript">
	        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
	        var disqus_shortname = 'blogadmin'; // required: replace example with your forum shortname

	        /* * * DON'T EDIT BELOW THIS LINE * * */
	        (function() {
	            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
	            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
	            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	        })();
	    </script>
	    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
	</div>
<?php else: ?>
	<?php header('Location: /blog'); ?>
<?php endif; ?>